export default {
    PERSON_FETCH_REQUESTED: 'PERSON_FETCH_REQUESTED',
    PERSON_FETCH_SUCCEEDED: 'PERSON_FETCH_SUCCEEDED',
    PERSON_FETCH_FAILED: 'PERSON_FETCH_FAILED',

    PEOPLE_FETCH_REQUESTED: 'PEOPLE_FETCH_REQUESTED',
    PEOPLE_FETCH_SUCCEEDED: 'PEOPLE_FETCH_SUCCEEDED',
    PEOPLE_FETCH_FAILED: 'PEOPLE_FETCH_FAILED',
};
